### PR TITLE
Add walking skeleton

### PR DESCRIPTION
**Pull request by mjaleman**
Fix: #1

### CODE REVIEW

**Review by glenjarvis — COMMENTED** [review]
Typically, I would give the feedback that the `.gitignore` file should be on the root level of the project. This is true for most project. And, we will probably need one on the top level even though this one exists here.

However, I have a feeling that this was auto-generated and was intentionally placed within the .idea directory.

No immediate action is needed. However, feel free to comment.

**Review by glenjarvis — CHANGES_REQUESTED** [review]
There are a few comments that don't need to be responded to. There are a few where requests are changed. Please review all and respond.

For over-all changes, please ensure the project name is `RothGar` and namespacing is `com.glenjarvis.rothgar`.

I had not considered that a logo would be needed at this hello world stage of the project. This is optional (but bill for the time if you do it). I've included two files:

 Logo100x100.png and paw_icon_152x152.svg to help with the logo files generated for the project.

Logo100x100

I am unable to include the SVG file here but can transmit separately.

Logo100x100

**Comment by glenjarvis** [comment]
It looks like my in-line comments were lost when the SVG upload error occurred submitting the last review.  Please also remove `local.properties` and add to `.gitignore`

There were about an hours worth of comments lost that I will review/regenerate in the next session. However, I can do that after these changes have been submitted.

**Comment by glenjarvis** [comment]
Because I lost the original GitHub review with inline comments for every file, let me generate a list of files to review:

These files have project name `RandomNumRoller` instead of `RothGar` within them:

* ./app/src/main/res/values-night/themes.xml
* ./app/src/main/res/values/themes.xml
* ./app/src/main/res/values/strings.xml
* ./app/src/main/AndroidManifest.xml
* ./settings.gradle
* ./.idea/modules.xml
* ./.idea/modules.xml
* ./.idea/.name
* ./.idea/modules/app/RandomNumRoller.app.iml
* ./.idea/modules/RandomNumRoller.iml

These filenames need renamed to use RothGar project name instead of RandomNumRoller:

* ./.idea/modules/app/RandomNumRoller.app.iml
* ./.idea/modules/RandomNumRoller.iml

These filenames have namespace `com.projectmalthorn.randomnumroller` instead of `com.glenjarvis.rothgar`:


* ./app/build.gradle
* ./app/src/androidTest/java/com/projectmalthorn/randomnumroller/ExampleInstrumentedTest.kt
* ./app/src/androidTest/java/com/projectmalthorn/randomnumroller/ExampleInstrumentedTest.kt
* ./app/src/test/java/com/projectmalthorn/randomnumroller/ExampleUnitTest.kt
* ./app/src/main/res/layout/activity_main.xml
* ./app/src/main/AndroidManifest.xml
* ./app/src/main/java/com/projectmalthorn/randomnumroller/MainActivity.kt

These filenames have different project name:

* ./app/src/androidTest/java/com/projectmalthorn
* ./app/src/test/java/com/projectmalthorn
* ./app/src/main/java/com/projectmalthorn

**Comment by glenjarvis** [comment]
Also, some of my inline comments on the generated bash script were lost, unfortunately: 

I see a reference to the project GradleWrapper but it doesn't exist. This is confirmed when trying to build:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

**Comment by mjaleman** [comment]
Just renamed packages and modules as well as some of the files that had references to RandomNumRoller. Let me know if I missed any. I attempted to remove the local.properties file as well. I think I was successful. I was also wondering if I should remove the .DS_Store files from git tracking.

**Comment by glenjarvis** [comment]
These changes look very good. 👍  I am able to build and run it and the emulator now shows Android Fire 10 API.

There are some files in `.gradle` that are derived (built from source and shouldn't be checked in). I thought possibly the entire directory was that way. However, I had to resync the project to build again.

So, I'm not certain how much of `.gradle` should be ignored (if not all of it). These files, for example differ:

- .gradle/6.5/executionHistory/executionHistory.bin
- gradle/6.5/executionHistory/executionHistory.lock
- .gradle/6.5/fileContent/fileContent.lock
- .gradle/6.5/fileHashes/fileHashes.bin
- .gradle/6.5/fileHashes/fileHashes.lock
- .gradle/6.5/fileHashes/resourceHashesCache.bin
- .gradle/6.5/javaCompile/javaCompile.lock
- .gradle/6.5/javaCompile/taskHistory.bin
- .gradle/buildOutputCleanup/buildOutputCleanup.lock
- .gradle/buildOutputCleanup/outputFiles.bin
- .gradle/checksums/checksums.lock
- .idea/compiler.xml
- .idea/misc.xml
- .idea/modules/app/RothGar.app.iml

As an example, these files certainly hold local settings:
- .idea/gradle.xml (e.g., `gradleHome` is a different direction)
- .idea/modules/app/RothGar.app.iml  (has paths such as `/Users/projectmalthorn`)

We may need to meet to figure out how much of this should be ignored and/or update the instructions on how to build/deploy.

**Comment by glenjarvis** [comment]
I also have been able to get the app installed on the Fire tablet. It's very straightforward after building.

So, this is good stuff. I think we're close to finished. We should probably find a time to meet, wrap up which of these files should be included, etc. And, then we can move onto the next GitHub issue.

**Comment by mjaleman** [comment]
Okie, will update the git ignore soon. As for times to meet I’m able to meet tomorrow between 5:30-6:30PM. And then Sunday any time after 11AM.

**Review by glenjarvis — APPROVED** [review]

**Pull request merged**
